### ISSUE TITLE
Unable to run sample NUnit test using Resharper runner

### ISSUE THREAD

**Issue by bytedreamer** [PragmaticFlow/NBomber#125]
When running a NBomber test using NUnit and Resharper, the following error occurs when registering scenarios.

 
```
System.ArgumentNullException : Value cannot be null.
Parameter name: element
   at System.Attribute.GetCustomAttributes(Assembly element, Type attributeType, Boolean inherit)
   at System.Attribute.GetCustomAttribute(Assembly element, Type attributeType, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttribute[T](Assembly element)
   at NBomber.Infra.Dependency.getMachineInfo()
   at NBomber.Infra.Dependency.create(ApplicationType appType)
   at NBomber.FSharp.NBomberRunner.runTest(NBomberRunnerContext context)
   at WebApi.Integration.Tests.Performance.OpenAccessLoadTests.<GetAccessLevelsLoadTest>d__8.MoveNext() in C:\Users\johorvat\CiscoSource\AccessControlApi\WebApi.Integration.Tests\Performance\OpenAccessLoadTests.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\AsyncInvocationRegion.cs:line 113
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunAsyncTestMethod(TestExecutionContext context) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Commands\TestMethodCommand.cs:line 96
```

I'm able to work around this issue by setting the AppDomain in the Constructor

```
            var manager = new AppDomainManager();
            var entryAssemblyField = manager.GetType()
                .GetField("m_entryAssembly", BindingFlags.Instance | BindingFlags.NonPublic);
            entryAssemblyField?.SetValue(manager, Assembly.GetCallingAssembly());

            var domain = AppDomain.CurrentDomain;
            var domainManagerField =
                domain.GetType().GetField("_domainManager", BindingFlags.Instance | BindingFlags.NonPublic);
            domainManagerField?.SetValue(domain, manager);
```

**Comment by AntyaDev** [comment]
Hi @bytedreamer ,
Can you please send your env details? OS,  framework ?

**Comment by bytedreamer** [comment]
I'm running it on Windows 10 with .NET 4.7.1 on VS 2017.

I haven't tried it without Resharper
