### ISSUE TITLE
Unhandled exception in `HtmlBuilder.toPrettyHtml`

### ISSUE THREAD

**Issue by vilinski** [PragmaticFlow/NBomber#127]
<details><summary>Expand to see the stack trace...</summary>

> Unhandled Exception: System.Xml.XmlException: An error occurred while parsing EntityName. Line 112, position 33.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, Int32 lineNo, Int32 linePos)
   at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32& charRefEndPos)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.FinishPartialValue()
   at System.Xml.XmlTextReaderImpl.get_Value()
   at System.Xml.Linq.XContainer.ContentReader.ReadContentFrom(XContainer rootContainer, XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XElement.ReadElementFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XElement.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XElement.Parse(String text, LoadOptions options)
   at NBomber.Infra.HtmlBuilder.toPrettyHtml(String html)
   at NBomber.DomainServices.Reporting.HtmlReport.print(Dependency dep, GlobalStats stats, DomainError[] failedAsserts)
   at NBomber.DomainServices.Reporting.Report.build(Dependency dep, GlobalStats stats, DomainError[] failedAsserts)
   at NBomber.DomainServices.NBomberRunner.createAndSaveReport(Dependency dep, NBomberContext context, GlobalStats globalStats, FSharpResult`2[] assertResults)
   at NBomber.DomainServices.NBomberRunner.run@75-9.Invoke(GlobalStats x)
   at Microsoft.FSharp.Core.ResultModule.Map[T,TResult,TError](FSharpFunc`2 mapping, FSharpResult`2 result)
   at NBomber.DomainServices.NBomberRunner.run$cont@55(Dependency dep, FSharpResult`2 matchValue, Unit unitVar)
   at NBomber.DomainServices.NBomberRunner.run(Dependency dep, NBomberContext context)
   at NBomber.FSharp.NBomberRunner.runInConsole(NBomberContext context)
   at Program.main(String[] argv) in C:\...\Program.fs:line 25

</details>

Does the `HtmlBuilder.toPrettyHtml` something essential or can it just return the input in error case? Worked for me in try/with

**Comment by vilinski** [comment]
Nevermind, hier is the fix: https://github.com/PragmaticFlow/NBomber/pull/128

**Comment by vilinski** [comment]
closing after merge
