### ISSUE TITLE
Question: Behavior of NBomber at the end of the duration

### ISSUE THREAD

**Issue by muskuloes** [PragmaticFlow/NBomber#166]
Hello,

Thanks for the nice framework, I enjoy using it. I am not an experienced C# developer and I will like some clarification. I am load testing a backend that processes request asynchronously. It seems like NBomber tries to generate reports even when a step isn't finished and eventually throws an exception when the test duration expires, without the reports being generated. Is there a way to completely wait for the steps to finish and then generate the reports?

Here is what the exception looks like:
`Unhandled Exception: System.ArgumentException: The input array was empty.
Parameter name: array
   at NBomber.Domain.Statistics.ScenarioStats.createByStepStats(Scenario scenario, StepStats[] stepsStats)
   at NBomber.DomainServices.ScenariosHost.getResults(StatisticsMeta meta, ScenarioRunner[] scnRunners)
   at NBomber.DomainServices.ScenariosHost.run@182-3.Invoke(Unit _arg3)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1)
   at Microsoft.FSharp.Control.AsyncPrimitives.Bind@495-1.Invoke(TResult result1)
   at Microsoft.FSharp.Control.AsyncActivation`1.OnSuccess(T result)
   at FsToolkit.ErrorHandling.AsyncResultCEExtensions.asyncResult@140-2.Invoke(AsyncActivation`1 ctxt) in /Users/tamizhvendan/DemystifyFpWorks/FsToolkit.ErrorHandling/src/FsToolkit.ErrorHandling/AsyncResultCE.fs:line 140
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit()
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronouslyInCurrentThread[a](CancellationToken cancellationToken, FSharpAsync`1 computation)
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at NBomber.DomainServices.NBomberRunner.run(Dependency dep, NBomberContext context)
   at NBomber.CSharp.NBomberRunner.RunTest(NBomberContext context)

**Comment by AntyaDev** [comment]
Hi @muskuloes 
How I can reproduce it?

Try to run with latest beta (0.15.0-beta)

**Comment by muskuloes** [comment]
Hi, we actually found a work around with our backend and `context.CancellationToken`.
The behavior happens to be nondetermistic, and I wasn't really able to come up with a good example to show that.
The code below provides a simplified illustration of our use case. We set a duration time on our  test execution, but we have some step(s) that might go over this time to complete. An exception was  sometimes thrown and the reports weren't generated.
```csharp
using System;
using System.Threading.Tasks;
using NBomber.Contracts;
using NBomber.CSharp;

namespace test.Scenarios
{
    public class HelloWorld
    {
        public static void Run()
        {
            var step = Step.Create("Hello World Step", async context =>
            {
                await Task.Delay(TimeSpan.FromMinutes(1));
                return Response.Ok();
            });
            
            var scenario = ScenarioBuilder.CreateScenario("Hello World Scenario", step)
                .WithWarmUpDuration(TimeSpan.Zero).WithDuration(TimeSpan.FromSeconds(10)).WithConcurrentCopies(2);

            NBomberRunner.RegisterScenarios(scenario).WithReportFileName("test-results").RunTest();
        }
    }
}
```

**Comment by AntyaDev** [comment]
fixed in v2
