### ISSUE TITLE
Error when installed with Paket

### ISSUE THREAD

**Issue by Akash-Mair** [PragmaticFlow/NBomber#410]
Hey guys!

I'm running into the below error when I install NBomber using paket.

```
rilog.Core.LoggingLevelSwitch, Boolean, Boolean, System.Nullable`1<System.TimeSpan>, Serilog.RollingInterval, Boolean, System.Nullable`1<Int32>, System.Text.Encoding, Serilog.Sinks.File.FileLifecycleHooks)'.
   at NBomber.Infra.Dependency.Logger.attachFileLogger@41(String folder, LoggerConfiguration config)
   at NBomber.Infra.Dependency.Logger.create(String folder, TestInfo testInfo, FSharpOption`1 createConfig, FSharpOption`1 configPath)
   at NBomber.Infra.Dependency.create(String reportFolder, TestInfo testInfo, ApplicationType appType, NodeType nodeType, NBomberContext context)
   at NBomber.DomainServices.NBomberRunner.run(NBomberContext context)
   at NBomber.FSharp.NBomberRunner.run(NBomberContext context)
   at Program.main(String[] argv)
```

No error when using nuget

**Comment by AntyaDev** [comment]
Hi, we don't use Packet, and that's why we haven't seen this issue.
Your PR is welcome)

**Comment by isaacabraham** [comment]
@Akash-Mair If you explicitly Serilog.Sinks.File to 4.1.0 and Spectre.Console to 0.38, this fixes both problems.
