### ISSUE TITLE
An InvalidOperationException (NBomber.FSharp.CommandLineArgs) error occurs when trying to execute NBomberRunner.

### ISSUE THREAD

**Issue by muskara** [PragmaticFlow/NBomber#418]
I get this error when I run the NBomber sample code to test it.

```csharp
static void Main(string[] args)
{
    // first, you need to create a step
    var step = Step.Create("step", async context =>
    {
        // you can define and execute any logic here,
        // for example: send http request, SQL query etc
        // NBomber will measure how much time it takes to execute your logic

        await Task.Delay(TimeSpan.FromSeconds(1));
        return Response.Ok();
    });

    // second, we add our step to the scenario
    var scenario = ScenarioBuilder.CreateScenario("hello_world", step);

    NBomberRunner
        .RegisterScenarios(scenario)
        .Run();

    //NBomberRunner Run() Error;
    /* System.InvalidOperationException: 'Type NBomber.FSharp.CommandLineArgs appears to be Immutable with invalid constructor. Check that constructor arguments have the same name and order of their underlying Type.  Constructor Parameters can be ordered as: '(config, infraconfig)'' */

}
```

StackTrace;
```
   at CommandLine.Core.InstanceBuilder.BuildImmutable[T](Type typeInfo, Maybe`1 factory, IEnumerable`1 specProps, IEnumerable`1 specPropsWithValue, List`1 setPropertyErrors)
   at CommandLine.Core.InstanceBuilder.<>c__DisplayClass0_0`1.<Build>b__5()
   at CommandLine.Core.InstanceBuilder.Build[T](Maybe`1 factory, Func`3 tokenizer, IEnumerable`1 arguments, StringComparer nameComparer, Boolean ignoreValueCase, CultureInfo parsingCulture, Boolean autoHelp, Boolean autoVersion, IEnumerable`1 nonFatalErrors)
   at CommandLine.Parser.ParseArguments[T](IEnumerable`1 args)
   at NBomber.FSharp.NBomberRunner.executeCliArgs(IEnumerable`1 args, NBomberContext context)
   at NBomber.FSharp.NBomberRunner.run(NBomberContext context)
   at NBomber.CSharp.NBomberRunner.Run(NBomberContext context)
```
- VS 2019 (I also tried with vscode but the result is the same. I even tried by setting up another virtual machine and still no results. I also tried with core 3.1 framework and it still didn't work.)
- .net 5.0 console app (C#)
- NBomber version 2.1.0

**Comment by AntyaDev** [comment]
Hi @muskara 
Sorry, but I can't reproduce it.
can you try to run it on Docker just to see that it's reproducible?
