### ISSUE TITLE
Seriolog exception

### ISSUE THREAD

**Issue by epitka** [PragmaticFlow/NBomber#466]
Did not see anything in documentation about Serilog, yet when running I get message

Unhandled exception. System.MissingMethodException: Method not found: 'Serilog.LoggerConfiguration Serilog.FileLoggerConfigurationExtensions.File(Serilog.Configuration.LoggerSinkConfiguration, System.String, Serilog.Events.LogEventLevel, System.Str
ing, System.IFormatProvider, System.Nullable`1<Int64>, Serilog.Core.LoggingLevelSwitch, Boolean, Boolean, System.Nullable`1<System.TimeSpan>, Serilog.RollingInterval, Boolean, System.Nullable`1<Int32>, System.Text.Encoding, Serilog.Sinks.File.FileL
ifecycleHooks)'.
   at NBomber.Infra.Logger.attachFileLogger@31(String folder, LoggerConfiguration config)
   at NBomber.Infra.Logger.create(String folder, TestInfo testInfo, FSharpOption`1 createConfig, FSharpOption`1 configPath)
   at NBomber.Infra.Dependency.create(String reportFolder, TestInfo testInfo, ApplicationType appType, NodeType nodeType, NBomberContext context)
   at NBomber.DomainServices.NBomberRunner.run(NBomberContext context)
   at NBomber.FSharp.NBomberRunner.run(NBomberContext context)
   at NBomber.CSharp.NBomberRunner.Run(NBomberContext context)
   at Program.<Main>$(String[] args)

**Comment by AntyaDev** [comment]
Hi @epitka 
Please use the latest v3 beta
