### ISSUE TITLE
Method not found: 'Serilog.LoggerConfiguration Serilog.FileLoggerConfigurationExtensions.File

### ISSUE THREAD

**Issue by brainboost** [PragmaticFlow/NBomber#478]
Very simple test case, taken from http example. I tried with several versions of NBomber starting from 2.1.2, the same exception:

```
System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'Serilog.LoggerConfiguration Serilog.FileLoggerConfigurationExtensions.File(Serilog.Configuration.LoggerSinkConfiguration, System.String, Serilog.Events.LogEventLevel, System.String, System.IFormatProvider, System.Nullable`1<Int64>, Serilog.Core.LoggingLevelSwitch, Boolean, Boolean, System.Nullable`1<System.TimeSpan>, Serilog.RollingInterval, Boolean, System.Nullable`1<Int32>, System.Text.Encoding, Serilog.Sinks.File.FileLifecycleHooks)'.
  Source=NBomber
  StackTrace:
   at NBomber.Infra.Logger.attachFileLogger@31(String folder, LoggerConfiguration config)
   at NBomber.Infra.Logger.create(String folder, TestInfo testInfo, FSharpOption`1 createConfig, FSharpOption`1 configPath)
   at NBomber.Infra.Dependency.create(String reportFolder, TestInfo testInfo, ApplicationType appType, NodeType nodeType, NBomberContext context)
   at NBomber.DomainServices.NBomberRunner.run(NBomberContext context)
   at NBomber.FSharp.NBomberRunner.run(NBomberContext context)
   at NBomber.CSharp.NBomberRunner.Run(NBomberContext context)
```
Setup: .net 6, xUnit, Serilog.AspNetCore 6.0.1 in projects' references

**Comment by AntyaDev** [comment]
Hi @brainboost 

Is it reproduced on the latest v3? https://www.nuget.org/packages/NBomber/3.0.0-rc2

**Comment by brainboost** [comment]
Hi @AntyaDev, thank you for response. No, I used stable ones, latest was 2.1.2. The rc2 looks ok, just verified
